### ISSUE TITLE
Icons may be being recreated every render

### ISSUE THREAD

**Issue by justinfagnani** [carbon-design-system/carbon-custom-elements#24]
This https://github.com/carbon-design-system/carbon-custom-elements/blob/master/src/components/icon/icon.ts#L39

looks to me like it'll cause icons to recreate their entire DOM every render. I would look into making a directive similar to lit-html's `unsafeHTML` that uses a `<template>` element and `innerHTML` to create some DOM, and cache the results based on the icon name, assuming the icon definitions don't change at runtime.

**Comment by asudoh** [comment]
Thanks @justinfagnani for reporting and providing us with a suggestion! I can see the problem of DOM recreation caused by [random ID-ref generation](https://github.com/carbon-design-system/carbon-custom-elements/blob/9241474/src/components/icon/icon.ts#L26-L28) that we need to fix it.

I saw it with [the example with `<title>`](https://carbon-custom-elements.netlify.com/?path=/story/icon--with-title) by adding DOM node removal breakpoint in DevTools and adding some code that causes another set of calls to `icon()`. But please let us know in case more tests should be done, better way to test it, etc.

<details>
 <summary>Code to trigger re-rendering of icon()</summary>

```javascript
diff --git a/src/components/icon/icon-story.ts b/src/components/icon/icon-story.ts
index e8295a4..beadaed 100644
--- a/src/components/icon/icon-story.ts
+++ b/src/components/icon/icon-story.ts
@@ -1,5 +1,6 @@
 import { html } from 'lit-html';
 import { storiesOf } from '@storybook/polymer';
+import { withKnobs, text } from '@storybook/addon-knobs';
 
 import Add16 from '@carbon/icons/lib/add/16';
 import Add20 from '@carbon/icons/lib/add/20';
@@ -9,9 +10,11 @@ import Add32 from '@carbon/icons/lib/add/32';
 import icon from './icon';
 
 storiesOf('Icon', module)
+  .addDecorator(withKnobs)
   .add(
     'Default',
     () => html`
+      <div foo="${text('foo', '')}"></div>
       ${icon(Add16)} ${icon(Add20)} ${icon(Add24)} ${icon(Add32)}
     `
   )
@@ -23,6 +26,7 @@ storiesOf('Icon', module)
           fill: #0062ff;
         }
       </style>
+      <div foo="${text('foo', '')}"></div>
       ${icon(Add16, { class: 'test-class' })} ${icon(Add20, { class: 'test-class' })} ${icon(Add24, { class: 'test-class' })}
       ${icon(Add32, { class: 'test-class' })}
     `
@@ -30,6 +34,7 @@ storiesOf('Icon', module)
   .add(
     'With aria-label',
     () => html`
+      <div foo="${text('foo', '')}"></div>
       ${icon(Add16, { 'aria-label': 'add' })} ${icon(Add20, { 'aria-label': 'add' })} ${icon(Add24, { 'aria-label': 'add' })}
       ${icon(Add32, { 'aria-label': 'add' })}
     `
@@ -37,6 +42,7 @@ storiesOf('Icon', module)
   .add(
     'With title',
     () => html`
+      <div foo="${text('foo', '')}"></div>
       ${icon(Add16, { title: 'add' })} ${icon(Add20, { title: 'add' })} ${icon(Add24, { title: 'add' })}
       ${icon(Add32, { title: 'add' })}
     `
```
</details>

Wrt icon definition - We are trying to interpolate [user-provided attributes](https://github.com/carbon-design-system/carbon-custom-elements/blob/9241474/src/components/icon/icon.ts#L22) with the template we generate. If there is a recommended way for that it'd be great to hear.
